"""Add receipt_number and balance_after to loan_payments

Revision ID: 06d65fec8cbc
Revises: 919a3a865523
Create Date: 2026-01-29 16:43:20.514853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d65fec8cbc'
down_revision = '919a3a865523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.drop_column('receipt_number')
        batch_op.drop_column('balance_after')

    # ### end Alembic commands ###
