"""add advance_balance column to loans

Revision ID: 076bc2b4d0f1
Revises: 2018cb036eaf
Create Date: 2026-02-25 16:36:13.314547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076bc2b4d0f1'
down_revision = '2018cb036eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance_balance', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('advance_balance')

    # ### end Alembic commands ###
