"""add_reschedule_date_to_loan_schedule_overrides

Revision ID: 2018cb036eaf
Revises: eaddc2aa7d1f
Create Date: 2026-02-19 17:14:26.608803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2018cb036eaf'
down_revision = 'eaddc2aa7d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedule_overrides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reschedule_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedule_overrides', schema=None) as batch_op:
        batch_op.drop_column('reschedule_date')

    # ### end Alembic commands ###
