"""Add loan_purpose and duration_weeks, rename loan_type to calculation type

Revision ID: 28ffa2dfc941
Revises: c8f81effd77a
Create Date: 2026-01-29 14:51:33.042184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ffa2dfc941'
down_revision = 'c8f81effd77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_purpose', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_weeks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('duration_weeks')
        batch_op.drop_column('loan_purpose')

    # ### end Alembic commands ###
