"""Add bank_book_image field to Customer model

Revision ID: 6e0a1ee5a23d
Revises: d987a35a28f2
Create Date: 2026-02-13 09:45:45.124182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0a1ee5a23d'
down_revision = 'd987a35a28f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_book_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('bank_book_image')

    # ### end Alembic commands ###
