"""Add documentation_fee column to loans

Revision ID: 6f560e6847da
Revises: 06d65fec8cbc
Create Date: 2026-01-29 16:49:01.755105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f560e6847da'
down_revision = '06d65fec8cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentation_fee', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('documentation_fee')

    # ### end Alembic commands ###
