"""Add duration_days column for Type 2 - 54 daily loan

Revision ID: 919a3a865523
Revises: 28ffa2dfc941
Create Date: 2026-01-29 15:41:25.619929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919a3a865523'
down_revision = '28ffa2dfc941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###
