"""Add can_verify_kyc permission to User model

Revision ID: a42fa3bde390
Revises: c59f4ba71ba1
Create Date: 2026-01-28 09:27:06.141894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42fa3bde390'
down_revision = 'c59f4ba71ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_verify_kyc', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_verify_kyc')

    # ### end Alembic commands ###
