"""Add document_path to loans

Revision ID: aa9c3f1935a3
Revises: a42fa3bde390
Create Date: 2026-01-29 13:15:16.537969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9c3f1935a3'
down_revision = 'a42fa3bde390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('document_path')

    # ### end Alembic commands ###
