"""Add bank information columns to customers table

Revision ID: c59f4ba71ba1
Revises: eb7e3d3d31df
Create Date: 2026-01-28 08:51:36.032817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59f4ba71ba1'
down_revision = 'eb7e3d3d31df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bank_account_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('bank_account_type')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_branch')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
