"""Add can_view_collection_reports permission

Revision ID: c8f81effd77a
Revises: 7b2199a277fc
Create Date: 2026-01-29 14:03:16.936268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f81effd77a'
down_revision = '7b2199a277fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_collection_reports', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_view_collection_reports')

    # ### end Alembic commands ###
