"""add_referred_by_field_to_loans

Revision ID: cc9ecdea3fb3
Revises: 139bdcd85f09
Create Date: 2026-01-30 09:45:16.466419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9ecdea3fb3'
down_revision = '139bdcd85f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Simplified to only add referred_by field
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_loans_referred_by', 'users', ['referred_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_referred_by', type_='foreignkey')
        batch_op.drop_column('referred_by')

    # ### end Alembic commands ###
