"""Re-add loan_purpose column to loans table

Revision ID: d987a35a28f2
Revises: 09271c8a10f1
Create Date: 2026-02-12 17:22:53.136080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd987a35a28f2'
down_revision = '09271c8a10f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_purpose', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('loan_purpose')
    # ### end Alembic commands ###
