"""Add guarantor_ids to loans

Revision ID: dfcedfc3b4cd
Revises: aa9c3f1935a3
Create Date: 2026-01-29 13:31:33.453618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcedfc3b4cd'
down_revision = 'aa9c3f1935a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guarantor_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('guarantor_ids')

    # ### end Alembic commands ###
