"""Add loan_schedule_overrides table

Revision ID: e3b4c982f1d5
Revises: 6e0a1ee5a23d
Create Date: 2026-02-18 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b4c982f1d5'
down_revision = '6e0a1ee5a23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_schedule_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('custom_due_date', sa.Date(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_number', name='unique_loan_installment_override')
    )
    with op.batch_alter_table('loan_schedule_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_schedule_overrides_loan_id'), ['loan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedule_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_schedule_overrides_loan_id'))

    op.drop_table('loan_schedule_overrides')
    # ### end Alembic commands ###
