"""Create default branch and populate data

Revision ID: ead4365ba91c
Revises: 5eb000dcc06a
Create Date: 2026-01-27 09:12:39.839208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead4365ba91c'
down_revision = '5eb000dcc06a'
branch_labels = None
depends_on = None


def upgrade():
    # Create default branch
    op.execute("""
    INSERT INTO branches (branch_code, name, address, phone, email, is_active, created_at, updated_at)
    VALUES ('MAIN', 'Main Branch', 'Default Branch Address', NULL, NULL, 1, datetime('now'), datetime('now'))
    """)
    
    # Get the ID of the default branch
    op.execute("SELECT id FROM branches WHERE branch_code = 'MAIN' LIMIT 1")
    
    # Populate branch_id for existing records
    op.execute("UPDATE customers SET branch_id = (SELECT id FROM branches WHERE branch_code = 'MAIN' LIMIT 1) WHERE branch_id IS NULL")
    op.execute("UPDATE loans SET branch_id = (SELECT id FROM branches WHERE branch_code = 'MAIN' LIMIT 1) WHERE branch_id IS NULL")
    op.execute("UPDATE investments SET branch_id = (SELECT id FROM branches WHERE branch_code = 'MAIN' LIMIT 1) WHERE branch_id IS NULL")
    op.execute("UPDATE pawnings SET branch_id = (SELECT id FROM branches WHERE branch_code = 'MAIN' LIMIT 1) WHERE branch_id IS NULL")
    
    # Make columns non-nullable
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pawnings', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pawnings', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
