"""add_drive_link_to_loans

Revision ID: eaddc2aa7d1f
Revises: e3b4c982f1d5
Create Date: 2026-02-19 17:05:57.610106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaddc2aa7d1f'
down_revision = 'e3b4c982f1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('drive_link')

    # ### end Alembic commands ###
