"""Add loan deactivation fields

Revision ID: f25d532fac6e
Revises: 553c5d8484b3
Create Date: 2026-02-06 15:58:32.008997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25d532fac6e'
down_revision = '553c5d8484b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deactivation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_loans_deactivated_by', 'users', ['deactivated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_deactivated_by', type_='foreignkey')
        batch_op.drop_column('deactivated_by')
        batch_op.drop_column('deactivation_date')
        batch_op.drop_column('deactivation_reason')

    # ### end Alembic commands ###
