"""Make nic_number field required for users

Revision ID: f8b915ee9925
Revises: 66509e971643
Create Date: 2026-02-06 14:52:59.160500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b915ee9925'
down_revision = '66509e971643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, set a default value for existing users with NULL nic_number
    op.execute("UPDATE users SET nic_number = 'PENDING' WHERE nic_number IS NULL OR nic_number = ''")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nic_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nic_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_purpose', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('customer_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.create_table('_alembic_tmp_customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('branch_id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('nic_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('customer_type', sa.TEXT(), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_primary', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone_secondary', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address_line2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('employer_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('monthly_income', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('kyc_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('kyc_verified_by', sa.INTEGER(), nullable=True),
    sa.Column('kyc_verified_date', sa.DATETIME(), nullable=True),
    sa.Column('nic_front_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nic_back_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('proof_of_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('additional_documents', sa.TEXT(), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.VARCHAR(length=50), nullable=True),
    sa.Column('guarantor_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('guarantor_nic', sa.VARCHAR(length=20), nullable=True),
    sa.Column('guarantor_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('guarantor_address', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bank_branch', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bank_account_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('bank_account_type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kyc_verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
